name: stats_env
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - pip:
      - numpy==1.24.2
      - pandas==2.0.0
      - scikit-learn==1.2.2
      - pdf2image==1.16.3
      - opencv-python==4.7.0.72
      - openai==0.27.4
      - flask==2.2.3
